apiVersion: v1
kind: Service
metadata:
  name: service-async-receiver-container-svc
  namespace: flowmanager
  labels:
    app: service-async-receiver-container
spec:
  ports:
  - name: http
    port: 18082
    targetPort: 18082
  selector:
    app: service-async-receiver-container
  type: LoadBalancer