apiVersion: v1
kind: Service
metadata:
  name: service-dispatcher-container-svc
  namespace: flowmanager
  labels:
    app: service-dispatcher-container
spec:
  ports:
  - name: http
    port: 18081
    targetPort: 18081
  selector:
    app: service-dispatcher-container
  type: LoadBalancer