apiVersion: v1
kind: Service
metadata:
  name: flask-sample-svc
  namespace: flowmanager
  labels:
    app: flask-sample-container
spec:
  ports:
  - name: http
    port: 19000
    targetPort: 19000
  selector:
    app: flask-sample-container
  type: LoadBalancer
