apiVersion: serving.knative.dev/v1 # Current version of Knative
kind: Service
metadata:
  name: svc-dispatcher 	# The name of the app
  namespace: flowmanager  	# The namespace the app will use
spec:
  template:
    metadata:
        annotations:
          autoscaling.knative.dev/minScale: "1"
          autoscaling.knative.dev/maxScale: "1"
    spec:
      containers:
        - image: leehs1979/svc-dispatcher:v4
          ports:
            - containerPort: 18081
          env:
            - name: FLOWMANAGER
              value: "http://34.64.115.117:28000/api/" 
