apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: receive-cloudevent-service
  namespace: flowmanager
spec:
  template:
    metadata:
        annotations:
          autoscaling.knative.dev/minScale: "1"
          autoscaling.knative.dev/maxScale: "1"
    spec:
      containers:
      -  # This corresponds to
         # https://github.com/knative/eventing-contrib/tree/main/cmd/event_display
         #image: gcr.io/knative-releases/knative.dev/eventing-contrib/cmd/event_display
         #image: jhc4guru/receive-cloudevent:latest
         image: leehs1979/receive-cloudevent:v1 
         ports:
          - containerPort: 8001
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: receive-cloudevent-trigger
  namespace: flowmanager
spec:
  broker: kafka-backed-broker
  filter:
    attributes:
      type: dev.knative.samples.t2
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: receive-cloudevent-service
