apiVersion: apps/v1
kind: Deployment
metadata:
  name: send-cloudevent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: send-cloudevent
  template:
    metadata:
      labels:
        app: send-cloudevent
    spec:
      containers:
        - name: send-cloudevent
          image: jhc4guru/send-cloudevent:latest
          ports:
          - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  #name: send-cloudevent
  name: send-cloudevent-svc
spec:
  #type: LoadBalancer
  type: NodePort
  selector:
    app: send-cloudevent
  ports:
  - protocol: TCP
    port: 7000
    targetPort: 8000
    nodePort: 30001

